### ISSUE TITLE
Demo code to deblur a single video

### ISSUE THREAD

**Issue by Championchess** [jixiang2016/dualBR#2]
Thanks for your amazing work! May I wonder whether you could also provide demo code that can be used to deblur a single input video and save the output?

**Comment by jixiang2016** [comment]
Not exactly know what you mean by "single input video" here.  If you refer to the frame sequence only with a blur view, I'm so sorry but that is not the targeted problem in this work.  If not, you have got a sequence with blur and RS views. Then just organize your data like the proposed dataset and run testing script. You shall get an upconverted output sequence in "output" folder under root directory.

I hope these can help you.
